services:
    oro_magento.orm.regions_repository:
        class: Doctrine\Persistence\ObjectRepository
        factory: ['@doctrine', getRepository]
        arguments:
            - OroMagentoBundle:Region
